### ISSUE TITLE
win7 64位打包不成功

### ISSUE THREAD

**Issue by fforever14** [nashaofu/dingtalk#123]
在执行npm run pack指令时,会报错
报错日志为npm-cache下的日志:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'pack' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prepack', 'pack', 'postpack' ]
5 info lifecycle dingtalk@2.0.7~prepack: dingtalk@2.0.7
6 info lifecycle dingtalk@2.0.7~pack: dingtalk@2.0.7
7 verbose lifecycle dingtalk@2.0.7~pack: unsafe-perm in lifecycle true
8 verbose lifecycle dingtalk@2.0.7~pack: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\dingtalk\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files (x86)\PuTTY\;C:\Program Files\nodejs\;D:\apache-ant-1.9.4\bin;D:\apache-maven-3.5.2\bin;D:\phantomjs-2.1.1\bin;C:\Program Files\Java\jdk1.7.0_80\bin;C:\Program Files\Git\cmd;C:\Program Files\MacType;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Donald\AppData\Roaming\npm
9 verbose lifecycle dingtalk@2.0.7~pack: CWD: E:\dingtalk
10 silly lifecycle dingtalk@2.0.7~pack: Args: [ '/d /s /c', 'electron-builder' ]
11 silly lifecycle dingtalk@2.0.7~pack: Returned: code: 1  signal: null
12 info lifecycle dingtalk@2.0.7~pack: Failed to exec pack script
13 verbose stack Error: dingtalk@2.0.7 pack: `electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid dingtalk@2.0.7
15 verbose cwd E:\dingtalk\release
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "pack"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error dingtalk@2.0.7 pack: `electron-builder`
22 error Exit status 1
23 error Failed at the dingtalk@2.0.7 pack script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by fforever14** [comment]
[2018-08-31T02_48_45_027Z-debug.log](https://github.com/nashaofu/dingtalk/files/2338697/2018-08-31T02_48_45_027Z-debug.log)
附上原始文件
