### ISSUE TITLE
无法联网使用，报代理错误

### ISSUE THREAD

**Issue by iminto** [nashaofu/dingtalk#129]
更新2.0.7后无法使用，报错如下。本机没有设置代理

(dingtalk:6296): libnotify-WARNING **: 11:49:08.862: Failed to connect to proxy
[6350:0920/114924.312312:ERROR:stunport.cc(88)] Binding request timed out from 192.168.90.x:51093 (wlp3s0)

(dingtalk:6296): libnotify-WARNING **: 11:49:33.885: Failed to connect to proxy

(dingtalk:6296): libnotify-WARNING **: 11:49:58.912: Failed to connect to proxy

**Comment by nashaofu** [comment]
能启动应用吗？里面应该也没有相关的设置的

**Comment by iminto** [comment]
能启动，就是一直卡在主界面，然后最终卡死被系统kill.
但其他应用都能正常上网。
我怀疑是运维捣的鬼，但不知道原理是什么，修改了下网络配置后好了。
这个issue可以关闭了。

**Comment by iminto** [comment]
又复现了  还是没明白程序为什么总会去连接proxy
报错堆栈
`(dingtalk:25860): libnotify-WARNING **: 16:48:06.758: Failed to connect to proxy
Error: Error: net::ERR_CONNECTION_TIMED_OUT
    at F.j [as _captureStackTrace] (/tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:175049)
    at new p (/tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:204729)
    at /tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:207818
    at t.AppImageUpdater._checkForUpdates (/tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:40441)
    at t.AppImageUpdater.checkForUpdates (/tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:39162)
    at /tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:2:246989
    at e.value (/tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:115550)
    at /tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:113298
    at i (/tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:114301)
    at /tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:114336
    at new Promise (<anonymous>)
    at new t (/tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:17571)
    at e.value (/tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:114240)
    at /tmp/.mount_dingtaTSwxhE/resources/app.asar/dist/main.js:1:113095
    at <anonymous>
`
