### ISSUE TITLE
Missing `app-udate.yml`

### ISSUE THREAD

**Issue by tzdybal** [nashaofu/dingtalk#169]
I'm unable to run 2.0.11, there is no GUI except tray-menu, and console shows following error:
```
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/dingtalk/resources/app-update.yml'
    at k.B [as _captureStackTrace] (/opt/dingtalk/resources/app.asar/dist/main.js:1:183994)
    at new p (/opt/dingtalk/resources/app.asar/dist/main.js:1:213706)
    at /opt/dingtalk/resources/app.asar/dist/main.js:1:216795
    at e.AppImageUpdater._checkForUpdates (/opt/dingtalk/resources/app.asar/dist/main.js:1:42919)
    at e.AppImageUpdater.checkForUpdates (/opt/dingtalk/resources/app.asar/dist/main.js:1:41634)
    at /opt/dingtalk/resources/app.asar/dist/main.js:2:286716
    at t.value (/opt/dingtalk/resources/app.asar/dist/main.js:1:125625)
    at /opt/dingtalk/resources/app.asar/dist/main.js:1:123019
    at <anonymous>
```

I'm using ArchLinux, and install dingtalk via AUR package - it's basically `.deb` release from github.

**Comment by nashaofu** [comment]
`app-udate.yml` only supports `AppImage` package,so this error is irrelevant.
But not working properly may be a network problem. 
Can you try to access https://im.dingtalk.com/?
Can the function inside the tray be used normally?  Such as "屏幕截图" (capture screenshot)

**Comment by tzdybal** [comment]
You're correct. I can't access https://im.dingtalk.com/, so the problem is caused by my temporary ISP.
When the address is accessible application works like a charm. I'm closing the issue.
