### ISSUE TITLE
arch无法运行appimage

### ISSUE THREAD

**Issue by deemoding** [nashaofu/dingtalk#94]
我系统是arch，不管自己编译还是直接下载你的 `dingtalk-2.0.5-x86_64.AppImage` ，都会报错
```bash
module.js:487        
    throw err;           
    ^                         
                                                                                                                     
Error: Cannot find module '/tmp/.mount_dingtaMGVhym/resources/electron.asar/browser/init.js' 
    at Function.Module._resolveFilename (module.js:485:15) 
    at Function.Module._load (module.js:437:25)       
    at Function.Module.runMain (module.js:605:10)          
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3 
```
但是，如果运行unpack下的 `dingtalk` ，能够运行，但是还会[报错](https://paste.ubuntu.com/p/TPByGTbhnS/)

**Comment by iminto** [comment]
我是manjaro，运行也是同样的报错

**Comment by mengzyou** [comment]
系统 openSUSE Leap 42.3 下，也报同样的错：  

```
→ ./dingtalk.AppImage 
module.js:487
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_dingtagQ7GWG/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
```

**Comment by DonnieLuo** [comment]
arch 一样的问题 只能退回2.0.4

**Comment by nashaofu** [comment]
2.0.4都是正常的吗？

**Comment by DonnieLuo** [comment]
是的 我2.0.4可以

**Comment by nashaofu** [comment]
我已经重新上传了AppImage文件，我在Ubuntn上测试是可以打开的，你们下载试试https://github.com/nashaofu/dingtalk/releases/latest，版本还是2.0.5

**Comment by TanghaohanSC** [comment]
sudo pacman -S aurman
aurman -S dingtalk-electron

**Comment by deemoding** [comment]
最新版已经可以正常打开了
