### ISSUE TITLE
18.04 ubuntu gnome shell  无法运行

### ISSUE THREAD

**Issue by Archer456** [nashaofu/dingtalk#96]
`cmd@TR:~/AppImage$ dingtalk-2.0.5-x86_64.AppImage 
Gtk-Message: 18:06:10.101: Failed to load module "unity-gtk-module"
module.js:487
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_dingtaCnGSwL/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
`

`cmd@TR:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
`
`cmd@TR:~$ screenfetch 
                          ./+o+-       cmd@TR
                  yyyyy- -yyyyyy+      OS: Ubuntu 18.04 bionic
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.15.0-22-generic
           .++ .:/++++++/-.+sss/`      Uptime: 37m
         .:++o:  /++++++++/:--:/-      Packages: 2357
        o:+o+:++.`..```.-/oo+++++/     Shell: bash
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 
 /+++//+:`oo+o               /::--:.   WM: GNOME Shell
 \+/+o+++`o++o               ++////.   WM Theme: Human-shell-theme
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Gnome-OSC-HS-(not-transparent) [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Papirus
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 12
         `:o+++ `ohhhhhhhhyo++os:      CPU: Intel Core i7-4700MQ @ 8x 3.4GHz [53.0°C]
           .o:`.syhhhhhhh/.oo++o`      GPU: intel
               /osyyyyyyo++ooo+++/     RAM: 4255MiB / 15960MiB
`

**Comment by seahurt** [comment]
我也是18.04 也是同样的错误

**Comment by nashaofu** [comment]
试一下这个命令呢：`sudo apt-get install --reinstall gtk2-engines-murrine:i386`

**Comment by nashaofu** [comment]
![image](https://user-images.githubusercontent.com/19303058/40988446-aada9fb0-691d-11e8-9ac5-a8ce5a50548c.png)
这是我在虚拟机上的截图，18.04 完美运行，请确保所有依赖都安装完整
首次安装报错信息，
```bash
sudo dpkg -i ./Desktop/dingtalk_2.0.5_amd64.deb 
正在选中未选择的软件包 dingtalk。
(正在读取数据库 ... 系统当前共安装有 159717 个文件和目录。)
正准备解包 .../dingtalk_2.0.5_amd64.deb  ...
正在解包 dingtalk (2.0.5-111) ...
dpkg: 依赖关系问题使得 dingtalk 的配置工作不能继续：
 dingtalk 依赖于 gconf2；然而：
  未安装软件包 gconf2。
 dingtalk 依赖于 libappindicator1；然而：
  未安装软件包 libappindicator1。

dpkg: 处理软件包 dingtalk (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 gnome-menus (3.13.3-11ubuntu1) 的触发器 ...
正在处理用于 desktop-file-utils (0.23-1ubuntu3) 的触发器 ...
正在处理用于 mime-support (3.60ubuntu1) 的触发器 ...
在处理时有错误发生：
 dingtalk
```
运行`sudo apt install -f`之后就解决了

**Comment by Archer456** [comment]
@nashaofu    我想弄好的是 appimage版本的   deb的话 我试下吧
